version: '3.8'
services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: magicstreamdb

  server:
    build:
      context: ./Server/MagicStreamMoviesServer
    ports:
      - "8081:8081"
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - DATABASE_NAME=magicstreamdb
      - ALLOWED_ORIGINS=http://localhost:5173
    depends_on:
      - mongo

  client:
    build:
      context: ./Client/magic-stream-client
    ports:
      - "5173:80"
    depends_on:
      - server

volumes:
  mongo-data:
